# bdf2psf
# Autogenerated from man page /usr/lib/jvm/default/man/man1/bdf2psf.1.gz
complete -c bdf2psf -l fb --description 'Generate font for framebuffer.'
complete -c bdf2psf -l log --description 'Record in the file  logfile any problems during the conversion.'

