# bdfresize
# Autogenerated from man page /usr/lib/jvm/default/man/man1/bdfresize.1.gz
complete -c bdfresize -s v --description 'Show the version number and exit.'
complete -c bdfresize -s b --description 'Specify the blackness.'
complete -c bdfresize -s w --description 'Specify the resize factor for the font width.'
complete -c bdfresize -s h --description 'Specify the resize factor for the font height.'
complete -c bdfresize -s f --description 'Same as ``-w factor -h factor\'\'.'

