# conky
# Autogenerated from man page /usr/lib/jvm/default/man/man1/conky.1.gz
complete -c conky -l alignment --description 'Text alignment on screen, {top,bottom,middle}_{left,right,middle} or none.'
complete -c conky -l config --description 'Config file to load instead of \\*(T<~/. config/conky/conky. conf\\*(T>.'
complete -c conky -l font --description 'Font to use.  Only available with build flag BUILD_X11 enabled.'
complete -c conky -l pause --description 'Time to pause/wait before actually starting Conky.'
complete -c conky -l text --description 'Text to render, remember single quotes, like -t \' $uptime \'.'
complete -c conky -l interval --description 'Update interval.'
complete -c conky -s V --description 'Prints version, build information and general info.  Exits after printing.'
complete -c conky -l window-id --description 'Window id to draw.  Only available with build flag BUILD_X11 enabled.'
complete -c conky -l display --description 'X11 display to use.  Only available with build flag BUILD_X11 enabled.'
complete -c conky -s t --description '.'
complete -c conky -l -------------------------------------------------------------------- --description 'USAGE: conky -t \'${sip_status}\' # print SIP status conky -t \'${sip_status 0}\'…'

