# deluged
# Autogenerated from man page /usr/lib/jvm/default/man/man1/deluged.1.gz
complete -c deluged -s c -l config --description 'Set the config directory location. SS Daemon Options.'
complete -c deluged -s p -l port --description 'Port daemon will listen on, default is 58846.'
complete -c deluged -s i -l interface --description 'Interface daemon will listen for bittorrent connections on, this should be an…'
complete -c deluged -s u -l ui-interface --description 'Interface daemon will listen for UI connections on, this should be an IP addr…'
complete -c deluged -s d -l do-not-daemonize --description 'Do not daemonize.'
complete -c deluged -s P -l pidfile --description 'Use pidfile to store process id  . SS Logging Options.'
complete -c deluged -s l -l logfile --description 'Output to designated logfile instead of stdout.'
complete -c deluged -s L -l loglevel --description 'Set the log level (default is error):  none, info, warning, error, critical, …'
complete -c deluged -s q -l quiet --description 'Sets the log level to \'none\', same as `-L none`  . SS Help Options.'
complete -c deluged -s v -l version --description 'Show program\'s version number and exit.'
complete -c deluged -s h -l help --description 'Show help message and exit.'

