# deluge
# Autogenerated from man page /usr/lib/jvm/default/man/man1/deluge.1.gz
complete -c deluge -s c -l config --description 'Set the config directory location. SS UI Options.'
complete -c deluge -s u -l ui --description 'The UI that you wish to launch, current options include: gtk, web or console.'
complete -c deluge -s s -l set-default-ui --description 'Sets the default UI to be run when no UI is specified.'
complete -c deluge -s a -l args --description 'Arguments to pass to a UI, -a \'--option args\'  . SS Logging Options.'
complete -c deluge -s l -l logfile --description 'Output to designated logfile instead of stdout.'
complete -c deluge -s L -l loglevel --description 'Set the log level (default is error):  none, info, warning, error, critical, …'
complete -c deluge -s q -l quiet --description 'Sets the log level to \'none\', same as `-L none`  . SS Help Options.'
complete -c deluge -s v -l version --description 'Show program\'s version number and exit.'
complete -c deluge -s h -l help --description 'Show help message and exit.'

