# deluge-web
# Autogenerated from man page /usr/lib/jvm/default/man/man1/deluge-web.1.gz
complete -c deluge-web -s c -l config --description 'Set the config directory location. SS Web Options.'
complete -c deluge-web -s b -l base --description 'Set the base path that the web ui is running on (proxying).'
complete -c deluge-web -s f -l fork --description 'Fork the web interface process into the background.'
complete -c deluge-web -s i -l interface --description 'Binds the webserver to a specific IP address.'
complete -c deluge-web -s p -l port --description 'Sets the port to be used for the webserver.'
complete -c deluge-web -l profile --description 'Profile the webserver code.'
complete -c deluge-web -l no-ssl --description 'Forces the webserver to disable ssl.'
complete -c deluge-web -l ssl --description 'Forces the webserver to use ssl  . SS Logging Options.'
complete -c deluge-web -s l -l logfile --description 'Output to designated logfile instead of stdout.'
complete -c deluge-web -s L -l loglevel --description 'Set the log level (default is error):  none, info, warning, error, critical, …'
complete -c deluge-web -s q -l quiet --description 'Sets the log level to \'none\', same as `-L none`  . SS Help Options.'
complete -c deluge-web -s v -l version --description 'Show program\'s version number and exit.'
complete -c deluge-web -s h -l help --description 'Show help message and exit.'

