# deluge-console
# Autogenerated from man page /usr/lib/jvm/default/man/man1/deluge-console.1.gz
complete -c deluge-console -s c -l config --description 'Set the config directory location. SS Logging Options.'
complete -c deluge-console -s l -l logfile --description 'Output to designated logfile instead of stdout.'
complete -c deluge-console -s L -l loglevel --description 'Set the log level (default is error):  none, info, warning, error, critical, …'
complete -c deluge-console -s q -l quiet --description 'Sets the log level to \'none\', same as `-L none`  . SS Help Options.'
complete -c deluge-console -s v -l version --description 'Show program\'s version number and exit.'
complete -c deluge-console -s h -l help --description 'Show help message and exit.'

