# gethostip
# Autogenerated from man page /usr/share/man/man1/gethostip.1.gz
complete -c gethostip -s f --description 'Full output.   Outputs the IP address in all supported formats.  Same as -xdn.'

