# lha
# Autogenerated from man page /usr/lib/jvm/default/man/man1/lha.1.gz
complete -c lha -s l --description 'List contents of the specified archive.'
complete -c lha -s v --description 'Verbosely list contents of the specified archive.'
complete -c lha -s t --description 'Test the integrity of the specified archive: decompress its contents and chec…'
complete -c lha -s e -s x --description 'Extract archive.'

