# mid3cp2
# Autogenerated from man page /usr/lib/jvm/default/man/man1/mid3cp2.1.gz
complete -c mid3cp2 -l verbose -s v --description 'Be verbose: state all operations performed, and list tags in source file.'
complete -c mid3cp2 -l write-v1 --description 'Write ID3v1 tags to the destination file, derived from the ID3v2 tags.'
complete -c mid3cp2 -l exclude-tag -s x --description 'Exclude a specific tag from being copied.  Can be specified multiple times.'
complete -c mid3cp2 -l merge --description 'Copy over frames instead of replacing the whole ID3 tag.'

