# moggsplit2
# Autogenerated from man page /usr/lib/jvm/default/man/man1/moggsplit2.1.gz
complete -c moggsplit2 -l extension --description 'Use the supplied extension when generating new files; the default is ogg.'
complete -c moggsplit2 -l pattern --description 'Use the supplied pattern when generating new files.'
complete -c moggsplit2 -l m3u --description 'Generate an m3u playlist along with the newly generated files.'

