# ndctl-check-labels
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ndctl-check-labels.1.gz
complete -c ndctl-check-labels -l bus --description '.'
complete -c ndctl-check-labels -s b --description '.'
complete -c ndctl-check-labels -s v --description '.'

