# ndctl-read-labels
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ndctl-read-labels.1.gz
complete -c ndctl-read-labels -l bus --description '.'
complete -c ndctl-read-labels -s b --description '.'
complete -c ndctl-read-labels -s v --description '.'
complete -c ndctl-read-labels -s o -l output --description '.'
complete -c ndctl-read-labels -s j -l json --description '.'

