# parcat
# Autogenerated from man page /usr/lib/jvm/default/man/man1/parcat.1.gz
complete -c parcat -s '#' --description 'Arguments following this will be sent to the file descriptor #.  E. g. Sp .'

