# shellcheck
# Autogenerated from man page /usr/lib/jvm/default/man/man1/shellcheck.1.gz
complete -c shellcheck -s s --description 'POSIX compliant (similar to checkbashisms).'
complete -c shellcheck -s a --description 'Emit warnings in sourced files.'
complete -c shellcheck -s C --description 'For TTY output, enable colors always, never or auto.  The default is auto.'
complete -c shellcheck -s e --description 'Explicitly exclude the specified codes from the report.'
complete -c shellcheck -s f --description 'Specify the output format of shellcheck, which prints its results in the stan…'
complete -c shellcheck -s S --description 'Specify minimum severity of errors to consider.'
complete -c shellcheck -s V --description 'Print version information and exit.'
complete -c shellcheck -s W --description 'For TTY output, show NUM wiki links to more information about mentioned warni…'
complete -c shellcheck -s x --description 'Follow `source\' statements even when the file is not specified as input.'

